#*************************************************************************
# Copyright (c) 2011 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/std/Makefile.

SRC_DIRS += $(STDDIR)/dev

DBD += devSoft.dbd

devAaiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAaiSoft.c
devAaoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAaoSoft.c
devAiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAiSoft.c
devAiSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAiSoftRaw.c
devAoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAoSoft.c
devAoSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAoSoftRaw.c
devBiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBiSoft.c
dbRecStd_SRCS += devBiSoftRaw.c
devBiDbState_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBiDbState.c
devBoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBoSoft.c
devBoSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBoSoftRaw.c
dbRecStd_SRCS += devBoDbState.c
devCalcoutSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devCalcoutSoft.c
devEventSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devEventSoft.c
devHistogramSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devHistogramSoft.c
devI64inSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devI64inSoft.c
devI64outSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devI64outSoft.c
devLiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLiSoft.c
devLoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLoSoft.c
devLsiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLsiSoft.c
devLsoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLsoSoft.c
devMbbiDirectSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiDirectSoft.c
devMbbiDirectSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiDirectSoftRaw.c
devMbbiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiSoft.c
devMbbiSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiSoftRaw.c
devMbboDirectSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboDirectSoft.c
devMbboDirectSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboDirectSoftRaw.c
devMbboSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboSoft.c
devMbboSoftRaw_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboSoftRaw.c
devPrintfSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devPrintfSoft.c
devSASoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devSASoft.c
devSiSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devSiSoft.c
devSoSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devSoSoft.c
devWfSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devWfSoft.c

devAiSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAiSoftCallback.c
devBiSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBiSoftCallback.c
devI64inSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devI64inSoftCallback.c
devLiSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLiSoftCallback.c
devMbbiDirectSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiDirectSoftCallback.c
devMbbiCallbackSoft_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbbiSoftCallback.c
devSiSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devSiSoftCallback.c

devAoSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devAoSoftCallback.c
devBoSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devBoSoftCallback.c
devCalcoutSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devCalcoutSoftCallback.c
devI64outSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devI64outSoftCallback.c
devLoSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLoSoftCallback.c
devLsoSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devLsoSoftCallback.c
devMbboSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboSoftCallback.c
devMbboDirectSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devMbboDirectSoftCallback.c
devPrintfSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devPrintfSoftCallback.c
devSoSoftCallback_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devSoSoftCallback.c

devGeneralTime_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devGeneralTime.c
devTimestamp_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devTimestamp.c
devStdio_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devStdio.c
devEnviron_CFLAGS += -DUSE_TYPED_DSET
dbRecStd_SRCS += devEnviron.c

dbRecStd_SRCS += asSubRecordFunctions.c

