TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#USR_CFLAGS += 

RECTYPES += xxxRecord.h
DBDEXPAND = exampleInclude.dbd
DBDNAME = exampleApp.dbd

LIBRARY_vxWorks = exampleLib

exampleLib_SRCS += xxxRecord.c
exampleLib_SRCS += devXxxSoft.c
exampleLib_SRCS += sncExample.c

exampleLib_SRCS += registerRecordDeviceDriver.c

LIBOBJS += registerRecordDeviceDriver.o

LIBOBJS += $(EPICS_BASE_BIN)/iocCore
LIBOBJS += $(EPICS_BASE_BIN)/seq

include ../baseLIBOBJS

#Note that the command line that builds the
#library $(LIBNAME) may be HUGE (>3kB)
#
include $(TOP)/configure/RULES_BUILD
#----------------------------------------
#  ADD RULES AFTER THIS LINE
