#
# $Id$
#

TOP=../..
include $(TOP)/config/CONFIG_APP

TARGETS = checkRelease CONFIG_APP_INCLUDE

include $(TOP)/config/RULES.Host

inc:: $(TARGETS)

CONFIG_APP_INCLUDE: $(wildcard $(TOP)/config/RELEASE*) $(TOP)/config/CONFIG_APP
	$(PERL) $(TOP)/config/convertRelease.pl $@

checkRelease:
	$(PERL) $(TOP)/config/convertRelease.pl $@

.PHONY :: checkRelease

