#!/bin/sh
#makeSoftLinks
#This shell program makes soft links to everything in MASTER_IOCAPPS/bin/*
#set -xv

SAVEDIR=$PWD
Cleanup() {
    cd $SAVEDIR
    rtncode=$1
    shift 1
    for MESSAGE
    do
        echo "$MESSAGE"
    done
    exit $rtncode
}
USAGE="Usage: makeSoftLinks MASTER_IOCAPPS dir"

if [ $# != 2 ]; then Cleanup 1 "Illegal number args" "$USAGE"; fi;
MASTER_IOCAPPS=$1
DIR=$2

if [ ! -d ${MASTER_IOCAPPS}/${DIR} ] ; then Cleanup 0 ; fi

FROM=${MASTER_IOCAPPS}/${DIR}
if [ -z "`ls ${FROM}`" ] ; then Cleanup 0 ; fi
if [ ! -d ${DIR} ] ; then
    echo "mkdir ${DIR}"
    mkdir ${DIR}
fi
cd ${DIR}
for FILE in `ls ${FROM}`
do
    if [ -d ${FROM}/${FILE} ] ; then
	$0 ${MASTER_IOCAPPS}/${DIR} ${FILE}
    elif [ -f ${FROM}/${FILE} ] ; then
        if [ ! -f "${FILE}" ]; then
        ln -s ${MASTER_IOCAPPS}/${DIR}/${FILE} ${FILE}
        fi
    else
        echo "${MASTER_IOCAPPS}/${DIR}/${FILE} Illegal."
    fi
done
Cleanup 0
