#
# $Id$
#

TOP=../..
include $(TOP)/config/CONFIG_APP

TARGETS = CONFIG_APP_INCLUDE

include $(TOP)/config/RULES.Vx

inc:: $(TARGETS)

CONFIG_APP_INCLUDE: $(wildcard $(TOP)/config/RELEASE*) $(TOP)/config/CONFIG_APP
	$(PERL) $(TOP)/config/convertRelease.pl -h $(HOST_ARCH) $@
