#
# Author: Jim Kowalkowski
# Date: 2/96
#
# $Id$
#
# $Log$
# Revision 1.3  1996/06/26 21:17:08  jhill
# fixed to match config in src
#
# Revision 1.2  1996/06/25 19:18:10  jbk
# moved from extensions to base - fixed trouble in dbMapper.cc
#
# Revision 1.1  1996/06/25 19:11:24  jbk
# new in EPICS base
#
#
# *Revision 1.2  1996/06/25 18:58:55  jbk
# *more fixes for the aitString management functions and mapping menus
# *Revision 1.1  1996/05/31 13:15:13  jbk
# *add new stuff
#
#

TOP=../..
# EPICS=/usr/local/epics/R3.12.2

include $(TOP)/config/CONFIG_BASE

include $(TOP)/config/RULES_ARCHS

