#
# Author: Jim Kowalkowski
# Date: 2/96
#
# $Id$
#
# $Log$
#
# *Revision 1.2  1996/06/25 18:58:55  jbk
# *more fixes for the aitString management functions and mapping menus
# *Revision 1.1  1996/05/31 13:15:13  jbk
# *add new stuff
#
#

EPICS=../../..
# EPICS=/usr/local/epics/R3.12.2

include $(EPICS)/config/CONFIG_EXTENSIONS

include $(EPICS)/config/RULES_ARCHS

