

/*************************************************************************\
* Copyright (c) 2002 The University of Chicago, as Operator of Argonne
*     National Laboratory.
* Copyright (c) 2002 The Regents of the University of California, as
*     Operator of Los Alamos National Laboratory.
* EPICS BASE Versions 3.13.7
* and higher are distributed subject to a Software License Agreement found
* in file LICENSE that is included with this distribution. 
\*************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

#include "shareLib.h"

/* 
 * The requests in this interface are typically ignored on OS that do not implement
 * POSIX signals. 
 */

struct epicsThreadOSD;

/* 
 * Required to avoid terminating a process which is blocking in a 
 * socket send() call when the SIGPIPE signal is generated by the OS.
 */
epicsShareFunc void epicsShareAPI epicsSignalInstallSigPipeIgnore ( void );

/* 
 * required only if shutdown() and close() do not interrupt a thread blocking in
 * a socket system call
 */
epicsShareFunc void epicsShareAPI epicsSignalInstallSigAlarmIgnore ( void );
epicsShareFunc void epicsShareAPI epicsSignalRaiseSigAlarm ( struct epicsThreadOSD * );

#ifdef __cplusplus
}
#endif

