EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

USR_CFLAGS = -ansi
VX_WARN_YES = -Wall -pedantic

MENUS += menuConvert.h

BPTS += bptTypeJdegC.db
BPTS += bptTypeJdegF.db
BPTS += bptTypeKdegC.db
BPTS += bptTypeKdegF.db


SRCS.c = \
	../cvtBpt.c

LIBOBJS = \
	cvtBpt.o

LIBNAME = pbtLib

include $(EPICS)/config/RULES.Vx

