TOP = ../../..
include $(TOP)/config/CONFIG_BASE

INC += cvtTable.h

SRCS.c = ../makeBpt.c
OBJS = makeBpt.o
PROD = makeBpt

include $(TOP)/config/RULES.Unix

$(PROD): $(OBJS)
	$(RM) $@
	$(LINK.c) -o $@ ${OBJS} $(LDLIBS)

