TOP = ../../..
include $(TOP)/config/CONFIG_BASE

INC := cvtTable.h

SRCS := makeBpt.c
PROD := makeBpt

MENUS += menuConvert.h

BPTS += bptTypeJdegC.dbd
BPTS += bptTypeJdegF.dbd
BPTS += bptTypeKdegC.dbd
BPTS += bptTypeKdegF.dbd

include $(TOP)/config/RULES.Host

$(BPTS): $(INSTALL_PROD)

