
TOP=../..

include $(TOP)/configure/CONFIG

MENUS += menuConvert.h

BPTS += bptTypeJdegC.dbd
BPTS += bptTypeJdegF.dbd
BPTS += bptTypeKdegC.dbd
BPTS += bptTypeKdegF.dbd

bptLibrary_SRCS = cvtBpt.c

LIBRARY = bptLibrary

include $(TOP)/configure/RULES_BUILD

