TOP = ../../..
include $(TOP)/config/CONFIG_BASE

USR_CFLAGS = -ansi
VX_WARN_YES = -Wall -pedantic

MENUS += menuConvert.h

BPTS += bptTypeJdegC.dbd
BPTS += bptTypeJdegF.dbd
BPTS += bptTypeKdegC.dbd
BPTS += bptTypeKdegF.dbd


SRCS.c = \
	../cvtBpt.c

LIBOBJS = \
	cvtBpt.o

LIBNAME = pbtLib

include $(TOP)/config/RULES.Vx

