
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

TESTPROD := resourceLibTest tsDLListBench tsDLListTest tsDLListTest \
		tsSLListBench tsSLListTest minmaxTest 

include $(TOP)/config/RULES.Host


