
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS = Com
SYS_PROD_LIBS_WIN32 := ws2_32 advapi32

TESTPROD := resourceLibTest tsDLListBench tsDLListTest tsDLListTest \
		tsSLListBench tsSLListTest minmaxTest

include $(TOP)/config/RULES.Host


