
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

SRCS.cc += ../resourceLibTest.cc
SRCS.cc += ../tsDLListBench.cc
SRCS.cc += ../tsDLListTest.cc
SRCS.cc += ../tsSLListBench.cc
SRCS.cc += ../tsSLListTest.cc

TARGETS += buildHere
#TARGETS += resourceLibTest
#TARGETS += tsDLListBench
#TARGETS += tsDLListTest
#TARGETS += tsSLListTest

include $(TOP)/config/RULES.Unix

buildHere: resourceLibTest tsDLListBench tsDLListTest tsSLListBench tsSLListTest

resourceLibTest: resourceLibTest.o
	$(LINK.cc) -o $@ $<

tsDLListBench: tsDLListBench.o
	$(LINK.cc) -o $@ $<

tsDLListTest: tsDLListTest.o
	$(LINK.cc) -o $@ $<

tsSLListBench: tsSLListBench.o
	$(LINK.cc) -o $@ $<

tsSLListTest: tsSLListTest.o
	$(LINK.cc) -o $@ $<

