
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS = Com

TESTPROD := resourceLibTest tsDLListBench tsDLListTest tsDLListTest \
		tsSLListBench tsSLListTest minmaxTest tsBTreeBench tsBTreeTest

include $(TOP)/config/RULES.Host


