TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#USR_CFLAGS +=
PROD_LIBS       += ca
PROD_LIBS       += Db
PROD_LIBS       += Com

#PROD_HOST = 

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

