TOP=../..
include $(TOP)/configure/CONFIG

PROD = caExample
caExample_SRCS += caExample.cc
#caExample_CFLAGS += 
#caExample_LDFLAGS += 
caExample_LIBS += ca Com
ca_LIB=$(EPICS_BASE_LIB)
Com_LIB=$(EPICS_BASE_LIB)

include $(TOP)/configure/RULES

