TOP=../..
include $(TOP)/configure/CONFIG

INC += egDefs.h
INC += erDefs.h
INC += ereventDefs.h

DBDINC += aaiRecord
DBDINC += aaoRecord
DBDINC += aiRecord
DBDINC += aoRecord
DBDINC += biRecord
DBDINC += boRecord
DBDINC += calcRecord
DBDINC += calcoutRecord
DBDINC += compressRecord
DBDINC += dfanoutRecord
DBDINC += egRecord
DBDINC += egeventRecord
DBDINC += erRecord
DBDINC += ereventRecord
DBDINC += eventRecord
DBDINC += fanoutRecord
DBDINC += gsubRecord
DBDINC += histogramRecord
DBDINC += longinRecord
DBDINC += longoutRecord
DBDINC += mbbiRecord
DBDINC += mbbiDirectRecord
DBDINC += mbboRecord
DBDINC += mbboDirectRecord
DBDINC += permissiveRecord
DBDINC += selRecord
DBDINC += seqRecord
DBDINC += stateRecord
DBDINC += stringinRecord
DBDINC += stringoutRecord
DBDINC += subRecord
DBDINC += subArrayRecord
DBDINC += waveformRecord

OBJS_IOC += aaiRecord
OBJS_IOC += aaoRecord
OBJS_IOC += aiRecord
OBJS_IOC += aoRecord
OBJS_IOC += biRecord
OBJS_IOC += boRecord
OBJS_IOC += calcRecord
OBJS_IOC += calcoutRecord
OBJS_IOC += compressRecord
OBJS_IOC += dfanoutRecord
OBJS_IOC += egRecord
OBJS_IOC += egeventRecord
OBJS_IOC += erRecord
OBJS_IOC += ereventRecord
OBJS_IOC += eventRecord
OBJS_IOC += fanoutRecord
OBJS_IOC += gsubRecord
OBJS_IOC += histogramRecord
OBJS_IOC += longinRecord
OBJS_IOC += longoutRecord
OBJS_IOC += mbbiRecord
OBJS_IOC += mbbiDirectRecord
OBJS_IOC += mbboRecord
OBJS_IOC += mbboDirectRecord
OBJS_IOC += permissiveRecord
OBJS_IOC += selRecord
OBJS_IOC += seqRecord
OBJS_IOC += stateRecord
OBJS_IOC += stringinRecord
OBJS_IOC += stringoutRecord
OBJS_IOC += subRecord
OBJS_IOC += subArrayRecord
OBJS_IOC += waveformRecord

include $(TOP)/configure/RULES

