
TOP=../..

include $(TOP)/configure/CONFIG


INC += egDefs.h
INC += erDefs.h
INC += ereventDefs.h

USR_INCLUDES = -I../drv/ansi -I../../drv/old

PROD += aaiRecord.o
PROD += aaoRecord.o
PROD += aiRecord.o
PROD += aoRecord.o
PROD += biRecord.o
PROD += boRecord.o
PROD += calcRecord.o
PROD += calcoutRecord.o
PROD += compressRecord.o
PROD += dfanoutRecord.o
PROD += egRecord.o
PROD += egeventRecord.o
PROD += erRecord.o
PROD += ereventRecord.o
PROD += eventRecord.o
PROD += fanoutRecord.o
PROD += gsubRecord.o
PROD += histogramRecord.o
PROD += longinRecord.o
PROD += longoutRecord.o
PROD += mbbiRecord.o
PROD += mbbiDirectRecord.o
PROD += mbboRecord.o
PROD += mbboDirectRecord.o
PROD += palRecord.o
PROD += permissiveRecord.o
PROD += pidRecord.o
PROD += pulseCounterRecord.o
PROD += pulseDelayRecord.o
PROD += pulseTrainRecord.o
PROD += selRecord.o
PROD += seqRecord.o
PROD += stateRecord.o
#PROD += steppermotorRecord.o
PROD += stringinRecord.o
PROD += stringoutRecord.o
PROD += subRecord.o
PROD += subArrayRecord.o
PROD += timerRecord.o
PROD += waveformRecord.o

include $(TOP)/configure/RULES_BUILD

