# AppVeyor configuration for EPICS Base

# Ralph Lange <ralph.lange@gmx.de>
# Copyright (c) 2016-2017 ITER Organization

# Version format
version: base-{branch}-{build}

#---------------------------------#
#       repository cloning        #
#---------------------------------#

# Called at very beginning, before repo cloning
init:
  # Set autocrlf to make batch files work
  - git config --global core.autocrlf true

# Set clone depth (do not fetch complete history)
clone_depth: 50

# Skipping commits affecting only specific files
skip_commits:
  files:
    - 'documentation/*'
    - 'templates/*'
    - '**/*.html'
    - '**/*.md'

#---------------------------------#
#   build matrix configuration    #
#---------------------------------#

# Build Configurations: dll/static, regular/debug
configuration:
  - dynamic
  - static
  - dynamic-debug
  - static-debug

# Environment variables: compiler toolchain
environment:
  matrix:
  - TOOLCHAIN: 10.0
  - TOOLCHAIN: 11.0
  - TOOLCHAIN: 12.0
  - TOOLCHAIN: 14.0
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLCHAIN: 2017
  - TOOLCHAIN: cygwin
  - TOOLCHAIN: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

# Platform: architecture
platform:
  - x86
  - x64

# Matrix configuration: allow specific failing jobs
matrix:
  exclude:
  # VS Express installs don't have the 64 bit compiler
  - platform: x64
    TOOLCHAIN: 10.0
  # Cygwin static-debug has compiler problems
  - configuration: static-debug
    TOOLCHAIN: cygwin


#---------------------------------#
#     building & testing          #
#---------------------------------#

install:
  - cmd: git submodule update --init --recursive
  - cmd: .ci/appveyor-prepare.bat

build_script:
  - cmd: .ci/appveyor-make.bat

test_script:
  - cmd: .ci/appveyor-make.bat runtests

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  - provider: Email
    to:
      - core-talk@aps.anl.gov
    on_build_success: false

  - provider: GitHubPullRequest
