
CAS = ../../..
TOP = $(CAS)/../..

include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com
#
# Added ws2_32 winmm user32 for the non-dll build
#
SYS_PROD_LIBS_WIN32 := ws2_32 advapi32 user32

SRCS += main.cc
SRCS += exServer.cc
SRCS += exPV.cc
SRCS += exVectorPV.cc
SRCS += exScalarPV.cc
SRCS += exAsyncPV.cc
SRCS += exChannel.cc

PROD := excas

include $(TOP)/config/RULES.Host

clean::
	@$(RM) excas 
	@$(RM) -rf Templates.DB
	@$(RM) core 

