#*************************************************************************
# Copyright (c) 2010 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/libCom/Makefile.

SRC_DIRS += $(LIBCOM)/timer
INC += epicsTimer.h
SRCS += epicsTimer.cpp
SRCS += timer.cpp
SRCS += timerQueue.cpp
SRCS += timerQueueActive.cpp
SRCS += timerQueueActiveMgr.cpp
SRCS += timerQueuePassive.cpp
