TOP=../../..

include $(TOP)/configure/CONFIG

LIBRARY_vxWorks = iocCore

iocCore_OBJS = \
	$(INSTALL_BIN)/asIocLibrary.a \
	$(INSTALL_BIN)/bptIocLibrary.a \
	$(INSTALL_BIN)/dbIocLibrary.a \
	$(INSTALL_BIN)/dbStaticIocLibrary.a \
	$(INSTALL_BIN)/caIocLibrary.a \
	$(INSTALL_BIN)/miscIocLibrary.a \
	$(INSTALL_BIN)/registryIocLibrary.a \
	$(INSTALL_BIN)/rsrvIocLibrary.a \
	$(INSTALL_BIN)/vxComLibrary.a \
	$(INSTALL_BIN)/vxDbLibrary.a

include $(TOP)/configure/RULES

