TOP=../../..

include $(TOP)/configure/CONFIG

LIBRARY_vxWorks = iocCore

iocCore_OBJS += $(INSTALL_BIN)/ComLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/caLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/dbStaticIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/registryIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/dbIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/asIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/miscIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/dbtoolsIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/rsrvIocLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/vxComLibrary.o
iocCore_OBJS += $(INSTALL_BIN)/vxDbLibrary.o

include $(TOP)/configure/RULES

