
TOP=../../..

include $(TOP)/configure/CONFIG

IOC_LIBRARY_vxWorks = iocCore

include $(TOP)/configure/RULES_BUILD

IOC_LIBRARY_OBJS = \
	$(INSTALL_BIN)/asLibrary \
	$(INSTALL_BIN)/caLib \
	$(INSTALL_BIN)/dbLib \
	$(INSTALL_BIN)/libCom \
	$(INSTALL_BIN)/dbStaticLib \
	$(INSTALL_BIN)/miscLib \
	$(INSTALL_BIN)/osiLibrary \
	$(INSTALL_BIN)/bptLibrary \
	$(INSTALL_BIN)/registryLibrary \
	$(INSTALL_BIN)/rsrvLib \
	$(INSTALL_BIN)/vxComLib \
	$(INSTALL_BIN)/vxDbLib

