EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

SRCS = ../ca_test.c ../calcTest.c ../recordTest.c
OBJS =

LIBOBJS =

TARGETS = ca_test calcTest recordTest

include $(EPICS)/config/RULES.Vx

%: %.o
	$(LINK.c) $@ $< $(LDLIBS)

