EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

SRCS.c = ../ca_test.c ../calcTest.c ../recordTest.c

TARGETS = ca_test.o calcTest.o recordTest.o

include $(EPICS)/config/RULES.Vx

