EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG

SRCS = ../ca_test.c ../calcTest.c ../recordTest.c
OBJS =

LIBOBJS =

TARGETS = ca_test calcTest recordTest

all: install

clean::
	rm -f $(TARGETS)

include $(EPICS)/config/RULES.Vx
