EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

USR_LDLIBS = -lca -lCom -lm -s
DEPLIBS = $(EPICS_BASE_LIB)/libca.a $(EPICS_BASE_LIB)/libCom.a

SRCS.c = \
	../ca_test.c \
	../iocLogServer.c \
	../startCArepeater.c

OBJS = \
	ca_test.o \
	iocLogServer.o \
	startCArepeater.o


PROD = \
	ca_test \
	iocLogServer \
	startCArepeater

include $(EPICS)/config/RULES.Unix

