#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

=head1 Menu menuOmsl

This menu is used for the C<OMSL> field of many output record types. It controls
whether the record will fetch an input value from its C<DOL> input link when
processed, which is useful when it is part of a closed loop control algorithm.
The C<supervisory> state means the input link will not be used, C<closed_loop>
enables the input link.

=menu menuOmsl

=cut

menu(menuOmsl) {
	choice(menuOmslsupervisory,"supervisory")
	choice(menuOmslclosed_loop,"closed_loop")
}
