#*************************************************************************
# Copyright (c) 2013 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

=head1 Menu menuSimm

This menu is used for Simulation Mode (SIMM) fields of input record types that
can fetch either raw or engineering values through their SIOL link.

=menu menuSimm

=cut

menu(menuSimm) {
	choice(menuSimmNO,"NO")
	choice(menuSimmYES,"YES")
	choice(menuSimmRAW,"RAW")
}
