TOP=../..
include $(TOP)/configure/CONFIG

# Product
#PROD_HOST = caExample
#caExample_SRCS += caExample.cc
#caExample_CFLAGS += 
#caExample_LDFLAGS += 
#caExample_LIBS += ca Com
#ca_LIB=$(EPICS_BASE_LIB)
#Com_LIB=$(EPICS_BASE_LIB)

# Library
#LIBRARY_HOST = abc
#abc_SRCS += abc.c
#abc_DLL_LIBS  = ca Com


include $(TOP)/configure/RULES


