TOP=../..

include $(TOP)/configure/CONFIG

TEMPLATES_DIR = makeBaseApp

TEMPLATES += top/Makefile
TEMPLATES += top/configure/RELEASE
TEMPLATES += top/configure/RULES.Db
TEMPLATES += top/configure/RULES.ioc
TEMPLATES += top/configure/RULES.iocBoot
TEMPLATES += top/configure/makeDbDepends.pl
TEMPLATES += top/configure/makeIocCdCommands.pl
TEMPLATES += top/configure/replaceVAR.pl

TEMPLATES += $(TOP)/configure/CONFIG
TEMPLATES += $(TOP)/configure/CONFIG.CrossCommon
TEMPLATES += $(TOP)/configure/CONFIG.Host.WIN32
TEMPLATES += $(TOP)/configure/CONFIG.Host.linux
TEMPLATES += $(TOP)/configure/CONFIG.Host.linux-x86
TEMPLATES += $(TOP)/configure/CONFIG.Host.solaris
TEMPLATES += $(TOP)/configure/CONFIG.Host.solaris-sparc
TEMPLATES += $(TOP)/configure/CONFIG.Host.sun4-68k
TEMPLATES += $(TOP)/configure/CONFIG.Host.win32-x86
TEMPLATES += $(TOP)/configure/CONFIG.Target.UnixCommon
TEMPLATES += $(TOP)/configure/CONFIG.Target.linux-x86
TEMPLATES += $(TOP)/configure/CONFIG.Target.mv162
TEMPLATES += $(TOP)/configure/CONFIG.Target.mv162lc
TEMPLATES += $(TOP)/configure/CONFIG.Target.mv167
TEMPLATES += $(TOP)/configure/CONFIG.Target.mv177
TEMPLATES += $(TOP)/configure/CONFIG.Target.solaris
TEMPLATES += $(TOP)/configure/CONFIG.Target.solaris-sparc
TEMPLATES += $(TOP)/configure/CONFIG.Target.sun4-68k
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorks-486
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorks-68040
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorks-68040lc
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorks-68060
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorks-ppc604
TEMPLATES += $(TOP)/configure/CONFIG.Target.vxWorksCommon
TEMPLATES += $(TOP)/configure/CONFIG.Target.win32-x86
TEMPLATES += $(TOP)/configure/CONFIG_BASE_VERSION
TEMPLATES += $(TOP)/configure/CONFIG_COMMON
TEMPLATES += $(TOP)/configure/CONFIG_ENV
TEMPLATES += $(TOP)/configure/CONFIG_EPICS_BASE
TEMPLATES += $(TOP)/configure/CONFIG_SITE
TEMPLATES += $(TOP)/configure/CONFIG_SITE.Host.WIN32-x86
TEMPLATES += $(TOP)/configure/CONFIG_SITE_ENV
TEMPLATES += $(TOP)/configure/RULES_ARCHS
TEMPLATES += $(TOP)/configure/RULES_BUILD
TEMPLATES += $(TOP)/configure/RULES_DIRS
TEMPLATES += $(TOP)/configure/RULES_TOP
TEMPLATES += $(TOP)/configure/tools/cp.pl
TEMPLATES += $(TOP)/configure/tools/findbase.pl
TEMPLATES += $(TOP)/configure/tools/getrel
TEMPLATES += $(TOP)/configure/tools/installEpics
TEMPLATES += $(TOP)/configure/tools/installEpics.pl
TEMPLATES += $(TOP)/configure/tools/makeMakefile.pl
TEMPLATES += $(TOP)/configure/tools/mkdir.pl
TEMPLATES += $(TOP)/configure/tools/mv.pl
TEMPLATES += $(TOP)/configure/tools/rm.pl
TEMPLATES += $(TOP)/configure/tools/testmkdir

TEMPLATES += top/exampleApp/Makefile
TEMPLATES += top/exampleApp/Db/Makefile
TEMPLATES += top/exampleApp/Db/Makefile.Host
TEMPLATES += top/exampleApp/Db/dbExample1.db
TEMPLATES += top/exampleApp/Db/dbExample2.substitutions
TEMPLATES += top/exampleApp/Db/dbExample2.template
TEMPLATES += top/exampleApp/src/Makefile
TEMPLATES += top/exampleApp/src/Makefile.Host
TEMPLATES += top/exampleApp/src/Makefile.Vx
TEMPLATES += top/exampleApp/src/caExample.c
TEMPLATES += top/exampleApp/src/devXxxSoft.c
TEMPLATES += top/exampleApp/src/exampleInclude.dbd
TEMPLATES += top/exampleApp/src/sncExample.st
TEMPLATES += top/exampleApp/src/xxxRecord.c
TEMPLATES += top/exampleApp/src/xxxRecord.dbd
TEMPLATES += top/exampleApp/src/base.dbd
TEMPLATES += top/exampleApp/src/baseLIBOBJS

TEMPLATES += top/simpleApp/Makefile
TEMPLATES += top/simpleApp/Db/Makefile
TEMPLATES += top/simpleApp/Db/Makefile.Host
TEMPLATES += top/simpleApp/src/Makefile
TEMPLATES += top/simpleApp/src/Makefile.Host
TEMPLATES += top/simpleApp/src/Makefile.Vx

TEMPLATES += top/simpleBoot/Makefile
TEMPLATES += top/simpleBoot/nfsCommands
TEMPLATES += top/simpleBoot/ioc/Makefile
TEMPLATES += top/simpleBoot/ioc/st.cmd

TEMPLATES += top/exampleBoot/Makefile
TEMPLATES += top/exampleBoot/nfsCommands
TEMPLATES += top/exampleBoot/ioc/Makefile
TEMPLATES += top/exampleBoot/ioc/st.cmd

SCRIPTS += makeBaseApp.pl

include $(TOP)/configure/RULES_BUILD

