#*************************************************************************
# Copyright (c) 2011 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/std/Makefile.

SRC_DIRS += $(STDDIR)/rec

DBDINC += aaiRecord
DBDINC += aaoRecord
DBDINC += aiRecord
DBDINC += aoRecord
DBDINC += aSubRecord
DBDINC += biRecord
DBDINC += boRecord
DBDINC += calcRecord
DBDINC += calcoutRecord
DBDINC += compressRecord
DBDINC += dfanoutRecord
DBDINC += eventRecord
DBDINC += fanoutRecord
DBDINC += histogramRecord
DBDINC += longinRecord
DBDINC += longoutRecord
DBDINC += mbbiRecord
DBDINC += mbbiDirectRecord
DBDINC += mbboRecord
DBDINC += mbboDirectRecord
DBDINC += permissiveRecord
DBDINC += selRecord
DBDINC += seqRecord
DBDINC += stateRecord
DBDINC += stringinRecord
DBDINC += stringoutRecord
DBDINC += subRecord
DBDINC += subArrayRecord
DBDINC += waveformRecord

DBD += stdRecords.dbd

stdRecords_DBD = $(patsubst %,%.dbd,$(DBDINC))

dbRecStd_SRCS += aaiRecord.c
dbRecStd_SRCS += aaoRecord.c
dbRecStd_SRCS += aiRecord.c
dbRecStd_SRCS += aoRecord.c
dbRecStd_SRCS += aSubRecord.c
dbRecStd_SRCS += biRecord.c
dbRecStd_SRCS += boRecord.c
dbRecStd_SRCS += calcRecord.c
dbRecStd_SRCS += calcoutRecord.c
dbRecStd_SRCS += compressRecord.c
dbRecStd_SRCS += dfanoutRecord.c
dbRecStd_SRCS += eventRecord.c
dbRecStd_SRCS += fanoutRecord.c
dbRecStd_SRCS += histogramRecord.c
dbRecStd_SRCS += longinRecord.c
dbRecStd_SRCS += longoutRecord.c
dbRecStd_SRCS += mbbiRecord.c
dbRecStd_SRCS += mbbiDirectRecord.c
dbRecStd_SRCS += mbboRecord.c
dbRecStd_SRCS += mbboDirectRecord.c
dbRecStd_SRCS += permissiveRecord.c
dbRecStd_SRCS += selRecord.c
dbRecStd_SRCS += seqRecord.c
dbRecStd_SRCS += stateRecord.c
dbRecStd_SRCS += stringinRecord.c
dbRecStd_SRCS += stringoutRecord.c
dbRecStd_SRCS += subRecord.c
dbRecStd_SRCS += subArrayRecord.c
dbRecStd_SRCS += waveformRecord.c

