#
# $Id$
#
#  Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.2  1996/06/25 21:47:56  jba
# Makefile includes now from base/src/config, removed all soft links
#
# Revision 1.1.1.1  1996/06/20 00:28:05  jhill
# ca server installation
#
# Revision 1.1  1994/09/07  19:26:34  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

DIRS = generic build example 

include $(TOP)/src/config/RULES_DIRS


