#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

SRCS.c += ../devAiTestAsyn.c
SRCS.c += ../devAoTestAsyn.c
SRCS.c += ../devBiTestAsyn.c
SRCS.c += ../devBoTestAsyn.c
SRCS.c += ../devEventTestIoEvent.c
SRCS.c += ../devHistogramTestAsyn.c
SRCS.c += ../devMbbiTestAsyn.c
SRCS.c += ../devMbboTestAsyn.c
SRCS.c += ../devSiTestAsyn.c
SRCS.c += ../devSoTestAsyn.c
SRCS.c += ../devWfTestAsyn.c

PROD = $(SRCS.c:../%.c=%.o)

include $(TOP)/config/RULES.Vx


