#*************************************************************************
# Copyright (c) 2010 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/libCom/Makefile.

SRC_DIRS += $(LIBCOM)/misc

INC += alarm.h
INC += alarmString.h
INC += adjustment.h
INC += cantProceed.h
INC += dbDefs.h
INC += epicsConvert.h
INC += epicsExit.h
INC += epicsStdlib.h
INC += epicsString.h
INC += epicsTypes.h
INC += shareLib.h
INC += epicsExport.h
INC += unixFileName.h
INC += locationException.h
INC += ipAddrToAsciiAsynchronous.h
INC += compilerDependencies.h
INC += epicsUnitTest.h
INC += testMain.h

# epicsVersion.h is created by this Makefile
INC += epicsVersion.h

SRCS += aToIPAddr.c
SRCS += adjustment.c
SRCS += cantProceed.c
SRCS += epicsConvert.c
SRCS += epicsExit.c
SRCS += epicsStdlib.c
SRCS += epicsString.c
SRCS += truncateFile.c
SRCS += ipAddrToAsciiAsynchronous.cpp
SRCS += epicsUnitTest.c
