#*************************************************************************
# Copyright (c) 2016 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/std/Makefile.

SRC_DIRS += $(STDDIR)/link

DBD += links.dbd

dbRecStd_SRCS += lnkConst.c
dbRecStd_SRCS += lnkCalc.c

HTMLS += links.html

