
TOP=../../..

include $(TOP)/configure/CONFIG

fdmgrTest_LIBS += Com
fdmgrTest_SRCS += fdmgrTest.c
fdmgrTest_LIBS += Com
fdmgrTest_SRCS += osiTimeTest.cc
PROD= osiTimeTest fdmgrTest

include $(TOP)/configure/RULES_BUILD

