
CAS = ../../..
TOP = $(CAS)/../..

include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com

SRCS += main.cc
SRCS += directoryServer.cc

PROD := caDirServ

include $(TOP)/config/RULES.Host

pcaDirServ: $(PROD_OBJS) $(PRODDEPLIBS)
	$(PURIFY) $(PROD_LINKER) $(PROD_OBJS) $(LDLIBS)

clean::
	@$(RM) caDirServ
	@$(RM) pcaDirServ
	@$(RM) -rf Templates.DB
	@$(RM) core 

