#*************************************************************************
# Copyright (c) 2013 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

=head1 Menu menuConvert

This menu defines the standard analog conversions which are included with Base.
IOC applications may add choices or replace the later choices in this menu,
although the first three choices must not be renamed or moved to different
positions. The breakpoint table name must exactly match the choice string
listed here.

=menu menuConvert

=cut

menu(menuConvert) {
	choice(menuConvertNO_CONVERSION,"NO CONVERSION")
	choice(menuConvertSLOPE,"SLOPE")
	choice(menuConvertLINEAR,"LINEAR")
	choice(menuConverttypeKdegF,"typeKdegF")
	choice(menuConverttypeKdegC,"typeKdegC")
	choice(menuConverttypeJdegF,"typeJdegF")
	choice(menuConverttypeJdegC,"typeJdegC")
	choice(menuConverttypeEdegF,"typeEdegF(ixe only)")
	choice(menuConverttypeEdegC,"typeEdegC(ixe only)")
	choice(menuConverttypeTdegF,"typeTdegF")
	choice(menuConverttypeTdegC,"typeTdegC")
	choice(menuConverttypeRdegF,"typeRdegF")
	choice(menuConverttypeRdegC,"typeRdegC")
	choice(menuConverttypeSdegF,"typeSdegF")
	choice(menuConverttypeSdegC,"typeSdegC")
}
