#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

=head1 Menu menuIvoa

This menu specifies the possibile actions to take when the INVALID alarm is
triggered. See individual record types for more information.

=menu menuIvoa

=cut

menu(menuIvoa) {
	choice(menuIvoaContinue_normally,"Continue normally")
	choice(menuIvoaDon_t_drive_outputs,"Don't drive outputs")
	choice(menuIvoaSet_output_to_IVOV,"Set output to IVOV")
}
