#*************************************************************************
# Copyright (c) 2012 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

=head1 Menu menuAlarmSevr

This menu defines the four possible alarm severities that EPICS records can
exhibit.  Note that it is not possible to add or remove severities just by
changing the choices defined here.

=menu menuAlarmSevr

=cut

menu(menuAlarmSevr) {
	choice(menuAlarmSevrNO_ALARM,"NO_ALARM")
	choice(menuAlarmSevrMINOR,"MINOR")
	choice(menuAlarmSevrMAJOR,"MAJOR")
	choice(menuAlarmSevrINVALID,"INVALID")
}
