#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

=head1 Menu menuYesNo

This menu is used to specify the C<NO> or C<YES> options of C<SIMM> field of 
many record types. 

Note that no other values for a field that uses menuYesNo are possible e.g. 
C<0.5>, C<MAYBE>, and C<NO WAY> are not possible choices for the field.
Also, the choices C<yes>, C<No>, and C<Yes> are not valid choices since they 
don't match the case of C<NO> or C<YES>.

=menu menuYesNo

=cut

menu(menuYesNo) {
	choice(menuYesNoNO,"NO")
	choice(menuYesNoYES,"YES")
}
