
TOP=../../..

include $(TOP)/configure/CONFIG

INC += camacLib.h
INC += module_types.h
#INC += task_params.h moved header to src/include
#INC += fast_lock. moved header to src/includeh

include $(TOP)/configure/RULES_BUILD

