
TOP=../..

include $(TOP)/configure/CONFIG


dbLib_SRCS = \
	dbLock.c\
	dbAccess.c\
	dbBkpt.c\
	dbConvert.c\
	dbFastLinkConv.c\
	dbNotify.c \
	iocInit.c\
	dbScan.c\
	dbEvent.c\
	dbTest.c\
	db_access.c\
	db_test.c\
	recGbl.c\
	callback.c\
	taskwd.c\
	dbCa.c \
        initHooks.c \
	dbcar.c 


LIBRARY = dbLib

include $(TOP)/configure/RULES_BUILD

dbCommon.h: ../dbCommonRecord.dbd ../dbCommon.dbd
	$(RM) $@
	$(EPICS_BASE)/bin/$(HOST_ARCH)/dbToRecordtypeH$(EXE) \
		$(USER_DBDFLAGS) $<
