EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE


SRCS.c = ../iocLogClient.c ../veclist.c 

LIBOBJS = veclist.o iocLogClient.o 

LIBNAME = vxComLib

include $(EPICS)/config/RULES.Vx

