TOP = ../../..
include $(TOP)/config/CONFIG_BASE

SRCS.c = ../iocLogClient.c ../veclist.c

#
# Tornado supplies this
#
ifeq ($(strip $(TORNADO)),NO)
SRCS.c += ../ldpp.c
endif

LIBOBJS = veclist.o iocLogClient.o

#
# Tornado supplies this
#
ifeq ($(strip $(TORNADO)),NO)
LIBOBJS += ldpp.o
endif

LIBOBJS_mips = symFindByNameMips.o


LIBNAME = vxComLib

#
# Tornado supplies this
#
ifeq ($(strip $(TORNADO)),NO)
SCRIPTS = vxldscript.MRI
endif

include $(TOP)/config/RULES.Vx

