TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of DB files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
#  Creation of <name>.dbd file from <name>Include.dbd
#DBDNAME += _APPNAME_.dbd

#----------------------------------------------------
# Add databases, templates, substitutions like this
#DB += _APPNAME_.db

#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += _APPNAME_.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
