# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of DB files using dbst (default: NO)
#DB_OPT = YES

#----------------------------------------------------
#  Optimization needs the name of the appropriate
#  dbd file (compare with ../src/Makefile.Vx)
#DBDNAME = _APPNAME_.dbd

#----------------------------------------------------
# Add databases, templates, substitutions like this
#DB += _APPNAME_.db

#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += _APPNAME_.template

#----------------------------------------------------
# The following lines are for local dbd expansion
#DBDEXPAND = _APPNAME_Include.dbd

include $(TOP)/config/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE
