#!/bin/sh 
#
# makeVersion - create the snc version module
#

VERSION=`cat $1`
DATE=`date`
echo	'/* sncVersion.c - version & date */'
echo	'/* Created by makeVersion */'
echo	'char *sncVersion = "@(#)SNC Version '${VERSION}': '${DATE}'";'
