TOP = ../../..
include $(TOP)/config/CONFIG_BASE

USR_CFLAGS =

SRCS.c = \
	../seq_main.c ../seq_ca.c ../seq_qry.c ../seq_task.c \
	../seq_mac.c ../seq_prog.c ../seq_if.c

OBJS = \
	seq_main.o seq_ca.o seq_qry.o seq_task.o \
	seq_mac.o seq_prog.o seq_if.o seqVersion.o

PROD = seq

include $(TOP)/config/RULES.Vx

clean::
	@$(RM) seqVersion.c

seq: $(OBJS)
	$(RM) $@
	$(LINK.c) $@ $(OBJS) $(LDLIBS)

seqVersion.c: ../Version
	$(RM) seqVersion.c
	sh ../makeSeqVersion ../Version > seqVersion.c
