#
# Makefile,v 1.2 1995/06/27 15:25:35 wright Exp
#
#  Lowest Level Directroy Makefile
#        by Janet Anderson
#
# Makefile,v
# Revision 1.2  1995/06/27  15:25:35  wright
# Brought over Andy's sequencer 1.9 files, compiled and created new seq and snc.
#
# Revision 1.1  1994/09/07  19:26:37  jba
# New file
#
#

EPICS=../../..

include $(EPICS)/config/CONFIG_BASE

include $(EPICS)/config/RULES_ARCHS

