EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG

USR_CFLAGS =

SRCS = \
	../seq_main.c ../seq_ca.c ../seq_qry.c ../seq_task.c \
	../seq_mac.c ../seq_prog.c seqVersion.c

OBJS = \
	seq_main.o seq_ca.o seq_qry.o seq_task.o \
	seq_mac.o seq_prog.o seqVersion.o

LIBOBJS =

PROD = seq

all: install

seqVersion.c: ../Version
	/bin/rm -f seqVersion.c
	sh ../makeSeqVersion ../Version > seqVersion.c

clean::
	rm -f seq seqVersion.c

include $(EPICS)/config/RULES.Vx
