#!/bin/sh
#
# makeSeqVersion - create the sequencer version module
#
VERSION=`cat $1`
DATE=`date`
echo	'/* seqVersion.c - version & date */'
echo	'/* Created by makeVersion */'
echo	'char *seqVersion = "@(#)SEQ Version '${VERSION}': '${DATE}'";'

