
TOP=../..

include $(TOP)/configure/CONFIG

dbStaticLib_SRCS = \
	dbYacc.c\
	dbPvdLib.c\
	dbStaticRun.c\
	dbStaticLib.c

LIBRARY = dbStaticLib

include $(TOP)/configure/RULES_BUILD

# Extra rule since dbLexRoutines.c is included in dbYacc.c
dbYacc$(OBJ): dbLex.c ../dbLexRoutines.c

clean::
	@$(RM) dbLex.c dbYacc.c 

#	EOF Makefile.Host for base/src/dbStatic
