TOP = ../../..
include $(TOP)/config/CONFIG_BASE

SRCS.c = \
	dbYacc.c \
	../dbPvdLib.c\
	../dbStaticRun.c\
	../dbStaticLib.c

OBJSdbLib = \
	dbYacc.o\
	dbPvdLib.o\
	dbStaticRun.o\
	dbStaticLib.o

PROD = dbStaticLib

include $(TOP)/config/RULES.Vx

# Extra rule since dbLexRoutines.c is included in dbYacc.c
dbYacc.o: dbLex.c ../dbLexRoutines.c

clean::
	@$(RM) dbLex.c dbYacc.c

dbStaticLib: $(OBJSdbLib)
	$(RM) $@
	$(LINK.c) $@ $(OBJSdbLib) $(LDLIBS)

