#
# $Id$
#
#  Base: Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1  1995/11/29 14:33:01  mrk
# Changes for replacing default.dctsdr by all ascii files
#
# Revision 1.1  1994/09/07  19:26:01  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

include $(TOP)/src/config/RULES_ARCHS

