#ifndef INCregistryRecordTypeh
#define INCregistryRecordTypeh

#include "shareLib.h"
struct dbRecordType;
struct rset;
struct dbBase;

typedef int (*computeSizeOffset)(struct dbRecordType *pdbRecordType);


typedef struct recordTypeLocation {
    struct rset *prset;
    computeSizeOffset sizeOffset;
}recordTypeLocation;
    

#ifdef __cplusplus
extern "C" {
#endif

epicsShareFunc int epicsShareAPI registryRecordTypeAdd(
    const char *name,recordTypeLocation *prtl);
epicsShareFunc recordTypeLocation * epicsShareAPI registryRecordTypeFind(
    const char *name);

/* The following function is generated by registerRecordDeviceDriver/pl */
epicsShareFunc int epicsShareAPI registerRecordDeviceDriver(
    struct dbBase *pdbbase);

#ifdef __cplusplus
}
#endif


#endif /* INCregistryRecordTypeh */
