
TOP=../../..

include $(TOP)/configure/CONFIG

INC += epicsDynLink.h

vxComLib_SRCS += iocLogClient.c
vxComLib_SRCS += veclist.c
vxComLib_SRCS += epicsDynLink.c

LIBRARY_vxWorks = vxComLib

include $(TOP)/configure/RULES_BUILD


