#
# $Id$
#
#  Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1  1994/09/07 19:26:13  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

include $(TOP)/src/config/RULES_ARCHS

