#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

INC += devCamac.h


#	SRCS.c += ../devAaiCamac.c
#	SRCS.c += ../devAiCamac.c
#	SRCS.c += ../devAaoCamac.c
#	SRCS.c += ../devAoCamac.c
#	SRCS.c += ../devBiCamac.c
#	SRCS.c += ../devBoCamac.c
#	SRCS.c += ../devLiCamac.c
#	SRCS.c += ../devLoCamac.c
#	SRCS.c += ../devMbbiCamac.c
#	SRCS.c += ../devMbbiDirectCamac.c
#	SRCS.c += ../devMbboCamac.c
#	SRCS.c += ../devMbboDirectCamac.c
#	SRCS.c += ../devWfCamac.c

PROD = $(SRCS.c:../%.c=%.o)

include $(TOP)/config/RULES.Vx


