TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

INC += devCamac.h


#	SRCS.c += ../devAaiCamac.c
#	SRCS.c += ../devAiCamac.c
#	SRCS.c += ../devAaoCamac.c
#	SRCS.c += ../devAoCamac.c
#	SRCS.c += ../devBiCamac.c
#	SRCS.c += ../devBoCamac.c
#	SRCS.c += ../devLiCamac.c
#	SRCS.c += ../devLoCamac.c
#	SRCS.c += ../devMbbiCamac.c
#	SRCS.c += ../devMbbiDirectCamac.c
#	SRCS.c += ../devMbboCamac.c
#	SRCS.c += ../devMbboDirectCamac.c
#	SRCS.c += ../devWfCamac.c

PROD = $(SRCS.c:../%.c=%.o)

include $(TOP)/config/RULES.Vx


