.TH freeList 1 "" "General Purpose Free List Library"
.ad b
.SH VERSION $Id$
.SH NAME
freeList.c - General Purpose memory free list library
.SH SYNOPSIS
.nf

freeListInitPvt	- Initialize a free list
freeListCalloc	- Allocate and initialize to zero a new element
freeListMalloc	- Allocate a new element
freeListFree	- Free an element,i.e. put on free list


void freeListInitPvt(void **ppvt,int size,int nmalloc);
void *freeListCalloc(void *pvt); 
void *freeListMalloc(void *pvt);
void freeListFree(void *pvt,void*pmem);

where :

pvt	- For private use by library. Caller must provide a "void *pvt"
size	- Size in butes of each element. Note that all elements must be same size
nmalloc	- Number of elements top allocate when regular malloc must be called.

.fi
.SH DESCRIPTION
This library can be used to allocate and free fixed size memory elements.
Free elements are maintained on a free list rather then being returned to
the heap via calls to free. When it is necessary to call malloc, memory can
be allocated in multiples of the element size.
.SH RETURNS
.nf
freeListCalloc and freeListMalloc return address of element allocated
or NULL if no more memory could be obtained via call to malloc
.SH INCLUDES
freeLib.h
.fi
