#*************************************************************************
# Copyright (c) 2010 UChicago Argonne LLC, as Operator of Argonne
#     National Laboratory.
# EPICS BASE is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

# This is a Makefile fragment, see src/libCom/Makefile.

SRC_DIRS += $(LIBCOM)/misc

INC += alarm.h
INC += alarmString.h
INC += adjustment.h
INC += cantProceed.h
INC += dbDefs.h
INC += epicsConvert.h
INC += epicsExit.h
INC += epicsStdlib.h
INC += epicsString.h
INC += epicsTypes.h
INC += shareLib.h
INC += epicsExport.h
INC += unixFileName.h
INC += locationException.h
INC += ipAddrToAsciiAsynchronous.h
INC += compilerDependencies.h
INC += epicsUnitTest.h
INC += testMain.h

# epicsVersion.h is created by this Makefile
INC += epicsVersion.h

Com_SRCS += alarmString.c
Com_SRCS += aToIPAddr.c
Com_SRCS += adjustment.c
Com_SRCS += cantProceed.c
Com_SRCS += epicsConvert.c
Com_SRCS += epicsExit.c
Com_SRCS += epicsStdlib.c
Com_SRCS += epicsString.c
Com_SRCS += truncateFile.c
Com_SRCS += ipAddrToAsciiAsynchronous.cpp
Com_SRCS += epicsUnitTest.c
