#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

SRCS.c += ../devBiMpv910.c
SRCS.c += ../devBoMpv902.c
SRCS.c += ../devMbbiDirectMpv910.c
SRCS.c += ../devMbbiMpv910.c
SRCS.c += ../devMbboDirectMpv902.c
SRCS.c += ../devMbboMpv902.c

PROD = $(SRCS.c:../%.c=%.o)

include $(TOP)/config/RULES.Vx


