#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************
TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

SRCS.c += ../devAiSymb.c
SRCS.c += ../devAoSymb.c
SRCS.c += ../devBiSymb.c
SRCS.c += ../devBoSymb.c
SRCS.c += ../devLiSymb.c
SRCS.c += ../devLoSymb.c
SRCS.c += ../devMbbiSymb.c
SRCS.c += ../devMbbiSymbRaw.c
SRCS.c += ../devMbboSymb.c
SRCS.c += ../devMbboSymbRaw.c
SRCS.c += ../devSiSymb.c
SRCS.c += ../devSoSymb.c
SRCS.c += ../devSymbFind.c
SRCS.c += ../devWfSymb.c

PROD = $(SRCS.c:../%.c=%.o)
LIBOBJS = $(SRCS.c:../%.c=%.o)
LIBNAME = symb


include $(TOP)/config/RULES.Vx
