TOP=../../../..

include $(TOP)/configure/CONFIG

TEMPLATES_DIR = makeBaseApp

TEMPLATES += top/caClientApp/Makefile
TEMPLATES += top/caClientApp/caExample.c
TEMPLATES += top/caClientApp/caMonitor.c

TEMPLATES += top/caPerlApp/Makefile
TEMPLATES += top/caPerlApp/cainfo.pl
TEMPLATES += top/caPerlApp/caget.pl
TEMPLATES += top/caPerlApp/caput.pl
TEMPLATES += top/caPerlApp/camonitor.pl

include $(TOP)/configure/RULES
