TOP=../../..

include $(TOP)/configure/CONFIG

MYMYSRCSS += devAiSoft.c
MYMYSRCSS += devAiSoftRaw.c
MYMYSRCSS += devAoSoft.c
MYMYSRCSS += devAoSoftRaw.c
MYMYSRCSS += devBiSoft.c
MYMYSRCSS += devBiSoftRaw.c
MYMYSRCSS += devBoSoft.c
MYMYSRCSS += devBoSoftRaw.c
MYMYSRCSS += devEventSoft.c
MYMYSRCSS += devHistogramSoft.c
MYMYSRCSS += devLiSoft.c
MYMYSRCSS += devLoSoft.c
MYMYSRCSS += devMbbiDirectSoft.c
MYMYSRCSS += devMbbiDirectSoftRaw.c
MYMYSRCSS += devMbbiSoft.c
MYMYSRCSS += devMbbiSoftRaw.c
MYMYSRCSS += devMbboDirectSoft.c
MYMYSRCSS += devMbboDirectSoftRaw.c
MYMYSRCSS += devMbboSoft.c
MYMYSRCSS += devMbboSoftRaw.c
MYMYSRCSS += devPtSoft.c
MYMYSRCSS += devSASoft.c
MYMYSRCSS += devSiSoft.c
MYMYSRCSS += devSoSoft.c
MYMYSRCSS += devWfSoft.c

PROD_vxWorks = $(MYMYSRCSS:%.c=%.o)

include $(TOP)/configure/RULES_BUILD


