TOP=../../..

include $(TOP)/configure/CONFIG

SRCS += devAiSoft.c
SRCS += devAiSoftRaw.c
SRCS += devAoSoft.c
SRCS += devAoSoftRaw.c
SRCS += devBiSoft.c
SRCS += devBiSoftRaw.c
SRCS += devBoSoft.c
SRCS += devBoSoftRaw.c
SRCS += devEventSoft.c
SRCS += devHistogramSoft.c
SRCS += devLiSoft.c
SRCS += devLoSoft.c
SRCS += devMbbiDirectSoft.c
SRCS += devMbbiDirectSoftRaw.c
SRCS += devMbbiSoft.c
SRCS += devMbbiSoftRaw.c
SRCS += devMbboDirectSoft.c
SRCS += devMbboDirectSoftRaw.c
SRCS += devMbboSoft.c
SRCS += devMbboSoftRaw.c
SRCS += devPtSoft.c
SRCS += devSASoft.c
SRCS += devSiSoft.c
SRCS += devSoSoft.c
SRCS += devWfSoft.c

IOC_PROD_vxWorks = $(SRCS:%.c=%.o)

include $(TOP)/configure/RULES_BUILD


