#
# $Id$
#
#  Base Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1  1995/07/27 14:22:44  winans
# first release
#
# Revision 1.1  1994/09/07  19:26:22  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

include $(TOP)/src/config/RULES_ARCHS

