TOP = ../../..
include $(TOP)/src/config/CONFIG_BASE

SRCS.c += ../bdt.c
SRCS.c += ../bdtServ.c
SRCS.c += ../bdtServName.c
SRCS.c += ../bdtServPv.c

OBJS += bdt.o
OBJS += bdtServ.o
OBJS += bdtServName.o
OBJS += bdtServPv.o

PROD = bdt

include $(TOP)/src/config/RULES.Vx

$(PROD): $(OBJS)
	$(RM) $@
	$(LINK.c) $@ $(OBJS) $(LDLIBS)
