
# $Log$
# Revision 1.3  1999/09/13 14:09:40  mrk
# for 3.14 only a single Makefile
#
# Revision 1.2  1997/03/05 21:16:21  jbk
# Fixes cvs log id at top
#

TOP=../../../..

include $(TOP)/configure/CONFIG

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com

SRCS += pvServ.cc

PROD :=pvServ

include $(TOP)/configure/RULES_BUILD

