
CAS = ../../..
TOP = $(CAS)/../..

include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com

SRCS += pvServ.cc

PROD :=pvServ

include $(TOP)/config/RULES.Host

clean::
	@$(RM) pvServ 
	@$(RM) -rf Templates.DB
	@$(RM) core 

