#
# $Id$
#

TOP = ../..

include $(TOP)/configure/CONFIG

DIRS += include 
DIRS += libvxWorks
DIRS += db
DIRS += drv
DIRS += rec
DIRS += dev
DIRS += devOpt
#DIRS += sequencer
DIRS += iocCore

include $(TOP)/configure/RULES_DIRS

