TOP=../../..

include $(TOP)/configure/CONFIG

INC += drvTS.h
INC += devLib.h

vxDb_SRCS += drvTS.c
vxDb_SRCS += devLib.c
vxDb_SRCS += devLibVxWorks.c
vxDb_SRCS += date.c

LIBRARY_vxWorks = vxDb

include $(TOP)/configure/RULES

