TOP=../../..

include $(TOP)/configure/CONFIG

INC += drvTS.h
INC += devLib.h
INC += tsDefs.h

vxDbLib_SRCS += drvTS.c
vxDbLib_SRCS += devLib.c
vxDbLib_SRCS += devLibVxWorks.c
vxDbLib_SRCS += tsSubr.c

LIBRARY_Ioc = vxDbLib

include $(TOP)/configure/RULES

