TOP=../../..

include $(TOP)/configure/CONFIG

INC += drvTS.h
INC += devLib.h
INC += tsDefs.h

vxDb_SRCS += drvTS.c
vxDb_SRCS += devLib.c
vxDb_SRCS += devLibVxWorks.c
vxDb_SRCS += tsSubr.c
vxDb_SRCS += date.c
vxDb_SRCS += drvTSinit.cpp

LIBRARY_vxWorks = vxDb

include $(TOP)/configure/RULES

