EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

INC += osiTime.h
INC += osiTimer.h
INC += resourceLib.h
INC += tsDLList.h
INC += tsSLList.h

include $(EPICS)/config/RULES.Unix
