#
# $Id$
#
#  Base: Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1.1.1  1996/06/20 22:15:56  jhill
# installed  ca server templates
#
# Revision 1.1  1994/09/07  19:26:01  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

include $(TOP)/src/config/RULES_ARCHS

