# SPDX-FileCopyrightText: 2000 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

# Makefile in extensions/configure directory

TOP=..

include $(TOP)/configure/CONFIG

TARGETS = $(CONFIG_TARGETS)

include $(TOP)/configure/RULES

