
TOP=../../..
 
include $(TOP)/configure/CONFIG
 
HOST_WARN=NO

USR_CFLAGS = -D_NO_PROTO

SRCS=	closure.c error.c lalr.c lr0.c main.c \
	mkpar.c output.c reader.c skeleton.c \
	symtab.c verbose.c warshall.c

PROD=antelope

include $(TOP)/configure/RULES_BUILD
