#       Makefile.Host  for  base/src/toolsComm/antelope
#
#

TOP = ../../../..
include $(TOP)/config/CONFIG_BASE

USR_CFLAGS = -D_NO_PROTO

SRCS=	closure.c error.c lalr.c lr0.c main.c \
	mkpar.c output.c reader.c skeleton.c \
	symtab.c verbose.c warshall.c

PROD=antelope

include $(TOP)/config/RULES.Host

#	EOF Makefile.Host
