EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

SRCS = ../epicsEnvParams.c ../epicsRelease.c

OBJS = epicsEnvParams.o epicsRelease.o

PROD = miscLib

include $(EPICS)/config/RULES.Vx

miscLib: $(OBJS)
	$(RM) $@
	$(LINK.c) $@ $(OBJS) $(LDLIBS)
