EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

SRCS.c = ../epicsRelease.c

OBJS =  epicsRelease.o

PROD = miscLib

include $(EPICS)/config/RULES.Vx

miscLib: $(OBJS)
	$(RM) $@
	$(LINK.c) $@ $(OBJS) $(LDLIBS)
