# SPDX-FileCopyrightText: 2000 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

# Makefile at the top of an extensions tree

TOP = .
include $(TOP)/configure/CONFIG
DIRS += configure
DIRS += src
include $(TOP)/configure/RULES_TOP


