
TOP=../..

include $(TOP)/config/CONFIG_BASE

DIRS += apsDev
DIRS += atDev
DIRS += avme9440Dev
DIRS += camacDev
DIRS += cometDev
DIRS += compumotorDev
DIRS += dvxDev
DIRS += gpibDev
DIRS += hpe1368Dev
DIRS += joergerDev
DIRS += kscV215Dev
DIRS += mizarDev
DIRS += mpvDev
DIRS += omsDev
DIRS += pentekDev
DIRS += softDev
DIRS += symbDev
DIRS += temp
DIRS += testDev
DIRS += vmiDev
DIRS += vxStatsDev
DIRS += xycomDev

include $(TOP)/config/RULES_DIRS

