#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
#     National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
#     Operator of Los Alamos National Laboratory.
# EPICS BASE Versions 3.13.7
# and higher are distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution. 
#*************************************************************************

TOP=../..

include $(TOP)/config/CONFIG_BASE

DIRS = apsDev
DIRS += atDev
DIRS += avme9440Dev
DIRS += camacDev
DIRS += cometDev
DIRS += compumotorDev
DIRS += dvxDev
DIRS += gpibDev
DIRS += hpe1368Dev
DIRS += joergerDev
DIRS += kscV215Dev
DIRS += mizarDev
DIRS += mpvDev
DIRS += omsDev
DIRS += pentekDev
DIRS += softDev
DIRS += symbDev
DIRS += testDev
DIRS += vmiDev
DIRS += vxStatsDev
DIRS += xycomDev

include $(TOP)/config/RULES_DIRS

