EPICS = ../../..
include $(EPICS)/config/CONFIG_vx

USR_CFLAGS = -ansi -I../drv
LDLIBS =

SRCS = \
	devAiDvx2502.c devAiSoft.c devAiSoftRaw.c \
	devAiSymb.c devAiTestAsyn.c devAiXy566Di.c \
	devAiXy566DiL.c devAiXy566Se.c devAoSoft.c \
	devAoSoftRaw.c devAoSymb.c devAoTestAsyn.c \
	devAoVmiVme4100.c devBiMpv910.c devBiSoft.c \
	devBiSoftRaw.c devBiTestAsyn.c devBiXVme210.c \
	devBoMpv902.c devBoSoft.c devBoSoftRaw.c \
	devBoTestAsyn.c devBoXVme220.c devCommonGpib.c \
	devEventSoft.c devEventTestIoEvent.c devHistogramSoft.c \
	devHistogramTestAsyn.c devLiSoft.c devLiSymb.c \
	devLoSoft.c devLoSymb.c devMbbiMpv910.c \
	devMbbiSoft.c devMbbiSoftRaw.c devMbbiTestAsyn.c \
	devMbbiXVme210.c devMbboMpv902.c devMbboSoft.c \
	devMbboSoftRaw.c devMbboTestAsyn.c devMbboXVme220.c \
	devPtSoft.c devSmCompumotor1830.c devSmOms6Axis.c \
	devSASoft.c devSiSoft.c devSiSymb.c \
	devSiTestAsyn.c devSoSoft.c devSoSymb.c \
	devSoTestAsyn.c devWfSoft.c devWfTestAsyn.c \
	devWfXy566Sc.c devAllenBradley.c devAt5Vxi.c \
	devMz8310.c devTimerMz8310.c \
	devVxiTDM.c devAiKscV215.c devXy240.c \
	devHpe1368a.c devAt8Fp.c devWfComet.c \
	devWfDvx2502.c devWfJoergerVtr1.c

OBJS = \
	$(OBDIR)/devAiDvx2502.o $(OBDIR)/devAiSoft.o \
	$(OBDIR)/devAiSoftRaw.o $(OBDIR)/devAiSymb.o \
	$(OBDIR)/devAiTestAsyn.o $(OBDIR)/devAiXy566Di.o \
	$(OBDIR)/devAiXy566DiL.o $(OBDIR)/devAiXy566Se.o \
	$(OBDIR)/devAoSoft.o $(OBDIR)/devAoSoftRaw.o \
	$(OBDIR)/devAoSymb.o $(OBDIR)/devAoTestAsyn.o \
	$(OBDIR)/devAoVmiVme4100.o $(OBDIR)/devBiMpv910.o \
	$(OBDIR)/devBiSoft.o $(OBDIR)/devBiSoftRaw.o \
	$(OBDIR)/devBiTestAsyn.o $(OBDIR)/devBiXVme210.o \
	$(OBDIR)/devBoMpv902.o $(OBDIR)/devBoSoft.o \
	$(OBDIR)/devBoSoftRaw.o $(OBDIR)/devBoTestAsyn.o \
	$(OBDIR)/devBoXVme220.o $(OBDIR)/devCommonGpib.o \
	$(OBDIR)/devEventSoft.o $(OBDIR)/devEventTestIoEvent.o \
	$(OBDIR)/devHistogramSoft.o $(OBDIR)/devHistogramTestAsyn.o \
	$(OBDIR)/devLiSoft.o $(OBDIR)/devLiSymb.o \
	$(OBDIR)/devLoSoft.o $(OBDIR)/devLoSymb.o \
	$(OBDIR)/devMbbiMpv910.o $(OBDIR)/devMbbiSoft.o \
	$(OBDIR)/devMbbiSoftRaw.o $(OBDIR)/devMbbiTestAsyn.o \
	$(OBDIR)/devMbbiXVme210.o $(OBDIR)/devMbboMpv902.o \
	$(OBDIR)/devMbboSoft.o $(OBDIR)/devMbboSoftRaw.o \
	$(OBDIR)/devMbboTestAsyn.o $(OBDIR)/devMbboXVme220.o \
	$(OBDIR)/devPtSoft.o $(OBDIR)/devSmCompumotor1830.o \
	$(OBDIR)/devSmOms6Axis.o $(OBDIR)/devSASoft.o \
	$(OBDIR)/devSiSoft.o $(OBDIR)/devSiSymb.o \
	$(OBDIR)/devSiTestAsyn.o $(OBDIR)/devSoSoft.o \
	$(OBDIR)/devSoSymb.o $(OBDIR)/devSoTestAsyn.o \
	$(OBDIR)/devWfSoft.o $(OBDIR)/devWfTestAsyn.o \
	$(OBDIR)/devWfXy566Sc.o $(OBDIR)/devAllenBradley.o \
	$(OBDIR)/devAt5Vxi.o $(OBDIR)/devMz8310.o \
	$(OBDIR)/devTimerMz8310.o \
	$(OBDIR)/devVxiTDM.o $(OBDIR)/devAiKscV215.o \
	$(OBDIR)/devXy240.o $(OBDIR)/devHpe1368a.o \
	$(OBDIR)/devAt8Fp.o $(OBDIR)/devWfComet.o \
	$(OBDIR)/devWfDvx2502.o $(OBDIR)/devWfJoergerVtr1.o

LIBOBJS =

PROD = $(OBDIR)/devSup

include $(EPICS)/config/RULES.Vx
