EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_BASE

INC += dbDefs.h
INC += camacLib.h
INC += epicsTypes.h
INC += epicsVersion.h
INC += gsd_sync_defs.h
INC += module_types.h
INC += shareLib.h
INC += createSoftLinks.sh 
INC += bsdProto.h

include $(EPICS)/config/RULES.Unix
