#
# $Id$
#
#  Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1  1996/01/25 21:38:30  mrk
# moved files from /base/include
#
# Revision 1.1  1994/09/07  19:26:32  jba
# New file
#
#

TOP=../..

include $(TOP)/src/config/CONFIG_BASE

include $(TOP)/src/config/RULES_ARCHS

