#
# $Id$
#
#  Lowest Level Directroy Makefile
#        by Janet Anderson
#
# $Log$
# Revision 1.1  1994/09/07  19:26:32  jba
# New file
#
#

EPICS=../../..

include $(EPICS)/config/CONFIG_BASE

include $(EPICS)/config/RULES_ARCHS

