name: Check EditorConfig

on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: EditorConfig-Action
        uses: greut/eclint-action@b9844795dd0b5fb19e3c60bd731fd3e548524b5c # v0
