name: Check EditorConfig

on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: EditorConfig-Action
        uses: greut/eclint-action@v0
