
# $Log$
# Revision 1.2  1997/05/13 14:22:59  jbk
# added comments at top
#

CAS = ../../..
TOP = $(CAS)/../..

include $(TOP)/config/CONFIG_BASE

PROD_LIBS := cas ca gdd Com

SRCS += mon.cc monAdl.cc monNode.cc monServer.cc

PROD := iocMonitor

include $(TOP)/config/RULES.Host

clean::
	@$(RM) iocMonitor 
	@$(RM) -rf Templates.DB
	@$(RM) core 

