
# $Log$

CAS = ../../..
TOP = $(CAS)/../..

include $(TOP)/config/CONFIG_BASE

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com

SRCS += mon.cc monAdl.cc monNode.cc monServer.cc

PROD := iocMonitor

include $(TOP)/config/RULES.Host

clean::
	@$(RM) iocMonitor 
	@$(RM) -rf Templates.DB
	@$(RM) core 

