
# $Log$
# Revision 1.3  1999/09/13 14:09:37  mrk
# for 3.14 only a single Makefile
#
# Revision 1.2  1997/05/13 14:22:58  jbk
# added comments at top
#

TOP=../../../..

include $(TOP)/configure/CONFIG

CXXCMPLR = STRICT

PROD_LIBS := cas ca gdd Com

SRCS += mon.cc monAdl.cc monNode.cc monServer.cc

PROD := iocMonitor

include $(TOP)/config/RULES_BUILD

clean::
	@$(RM) iocMonitor 
	@$(RM) -rf Templates.DB
	@$(RM) core 

