
# $Log$
# Revision 1.3  1999/09/13 14:09:37  mrk
# for 3.14 only a single Makefile
#
# Revision 1.2  1997/05/13 14:22:58  jbk
# added comments at top
#

TOP=../../../..

include $(TOP)/configure/CONFIG

include $(TOP)/configure/RULES_ARCHS

