#!/bin/sh
#
#  $Id$
#
#           Author: Matthew Needes
#
#  $Log$
#  Revision 1.1  1996/02/20 20:58:42  jba
#  Moved tools to src/tools dir. base/tools dir removed.
#
#  Revision 1.13  1996/01/25 21:03:20  mrk
#  Changes for new all ascii database definitions
#
# Revision 1.12  1995/08/18  15:26:05  jba
# Added pathname to GetVar
#
# Revision 1.11  1995/08/17  20:35:20  jba
# EPICS added on calls to GetVar
#
# Revision 1.10  1995/04/26  16:20:35  jba
# Added date to .current_rel_hist file output
#
# Revision 1.9  1995/03/30  23:16:07  jba
# Changed example comment
#
# Revision 1.8  1994/09/15  22:06:36  mcn
# Removed -h from test flags.
#
# Revision 1.7  1994/09/07  20:59:17  mcn
# Revamped GetVar, modified scripts for new GetVar.
#
# Revision 1.6  1994/09/07  19:08:52  jba
# Modified to work with extensions and do depends
#
# Revision 1.5  1994/08/21  00:56:43  mcn
# New Stuff
#
# Revision 1.4  1994/08/16  17:20:45  mcn
# exported variable
#
# Revision 1.3  1994/08/16  16:12:19  mcn
# Added GetVar, made use of 'ln' compatible with SYSV Unix.
#
# Revision 1.2  1994/08/02  18:36:30  mcn
# Support new configuration.
#
# Revision 1.1  1994/07/14  16:17:36  mcn
# Modified to support structure of base, made more intelligent (mcn)
#

USAGE="Usage:
        getrel <EpicsNode> 

ex:     getrel  /usr/local/epics/R3.12
        --------- OR -----------
        getrel  ~/epics 

"

# one arg
if [ $# -lt 1 ]; then
        cat <<!message

$USAGE
!message
        exit
fi

EPICS=${1}
BASE=${1}/base

if [ ! -d ${BASE}/bin -o \
     ! -d ${BASE}/db ]; then
        cat <<-!usage
    $USAGE

    ${EPICS} does not appear to be an EPICS root tree...

!usage
    exit 1
fi


/bin/rm -f \
	epics \
	base \
	config \
	target* \
	vxWorks* \
	vw

ln -s ${EPICS} epics


touch .current_rel_hist
echo ${EPICS} - `date` >> .current_rel_hist

exit 0
