#	base/src/tools/Makefile.Host
#

TOP = ../../..
include $(TOP)/config/CONFIG_BASE

#	install these scripts:
#

SCRIPTS += $(subst ../,,$(wildcard ../*.pl))
SCRIPTS += installEpics

include $(TOP)/config/RULES.Host

#	EOF base/src/tools/Makefile.Host
