TOP = ../../..
include $(TOP)/config/CONFIG_BASE

PROD = installEpics
SCRIPTS += getrel 
SCRIPTS += makeBaseApp

default: all

inc:: $(INSTALL_BIN)/installEpics

include $(TOP)/config/RULES.Unix

$(INSTALL_BIN)/installEpics: ../installEpics
	@echo "Installing $@"
	@test -d $(INSTALL_LOCATION_BIN) || mkdir $(INSTALL_LOCATION_BIN)
	@test -d $(INSTALL_BIN) || mkdir $(INSTALL_BIN)
	@$< -m 555 $< $(INSTALL_BIN)

