#	base/src/tools/Makefile.Host
#

TOP = ../../..
include $(TOP)/config/CONFIG_BASE

#	install these scripts:
#
SCRIPTS       := makeBaseApp installEpics

include $(TOP)/config/RULES.Host

#	EOF base/src/tools/Makefile.Host
